import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>Index</div>
      <Link href={"/dashboard"}>
        <a>Dashboard</a>
      </Link>
      <Link href={"/signin"}>
        <a>SignIn</a>
      </Link>
    </>
  );
};

export default Home;
